package com.goofy.goober.style

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFF68D3FF)
val md_theme_dark_onPrimary = Color(0xFF003546)
val md_theme_dark_primaryContainer = Color(0xFF004D64)
val md_theme_dark_onPrimaryContainer = Color(0xFFBEE9FF)
val md_theme_dark_secondary = Color(0xFFB4CAD6)
val md_theme_dark_onSecondary = Color(0xFF1F333C)
val md_theme_dark_secondaryContainer = Color(0xFF354A53)
val md_theme_dark_onSecondaryContainer = Color(0xFFD0E6F2)
val md_theme_dark_tertiary = Color(0xFFC6C2EA)
val md_theme_dark_onTertiary = Color(0xFF2F2D4D)
val md_theme_dark_tertiaryContainer = Color(0xFF454364)
val md_theme_dark_onTertiaryContainer = Color(0xFFE3DFFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1E)
val md_theme_dark_onBackground = Color(0xFFE1E2E4)
val md_theme_dark_surface = Color(0xFF191C1E)
val md_theme_dark_onSurface = Color(0xFFE1E2E4)
val md_theme_dark_surfaceVariant = Color(0xFF40484C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C8CD)
val md_theme_dark_outline = Color(0xFF8A9297)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1E)
val md_theme_dark_inverseSurface = Color(0xFFE1E2E4)
val md_theme_dark_inversePrimary = Color(0xFF006684)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF68D3FF)
val md_theme_dark_outlineVariant = Color(0xFF40484C)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF62757F)
